---

- name: "fail unless we run on a supported distribution"
  fail:
    msg: "Unfortunately, the 'postfix'-role is not supported on {{ ansible_distribution_release }}! :-("
  when:
    - "ansible_distribution_release|lower not in postfix_simple_supported_distro_list"

- name: "fail unless credentials are provided"
  fail:
    msg: "This role only works if you provide postfix_simple_user as well as postfix_simple_password!"
  when:
    - "postfix_simple_user is not defined or not postfix_simple_user or postfix_simple_password is not defined or not postfix_simple_password"

- name: "install prerequisite packages"
  apt:
    default_release: "{{ postfix_simple_pre_default_release }}"
    name: "{{ item }}"
    state: "present"
  with_items:
    - "{{ postfix_simple_pre_package_list }}"
